# Generated by Django 4.2.7 on 2025-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_id', models.IntegerField(unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('topic', models.CharField(choices=[('chỉnh hình', 'Chỉnh hình'), ('nhi khoa', 'Nhi khoa'), ('tim mạch', 'Tim mạch'), ('tiêu hóa', 'Tiêu hóa'), ('hô hấp', 'Hô hấp'), ('thần kinh', 'Thần kinh'), ('da liễu', 'Da liễu'), ('sản phụ khoa', 'Sản phụ khoa'), ('y tế chung', 'Y tế chung')], default='y tế chung', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic'], name='healthcare__topic_be067b_idx'), models.Index(fields=['qa_id'], name='healthcare__qa_id_e88b40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='healthcare__title_a9faf6_idx'), models.Index(fields=['created_at'], name='healthcare__created_8500f9_idx')],
            },
        ),
    ]
