# Generated by Django 6.0 on 2025-12-29 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("query", models.TextField(verbose_name="Câu hỏi")),
                ("answer", models.TextField(verbose_name="Câu trả lời")),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Chuyên khoa"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=0.0, verbose_name="Độ tin cậy"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Thời gian"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử chat",
                "verbose_name_plural": "Lịch sử chat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("text", models.TextField()),
                ("slug", models.SlugField(blank=True, max_length=500)),
                ("views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bài viết",
                "verbose_name_plural": "Bài viết",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="chatbot_art_title_3ed020_idx"),
                    models.Index(
                        fields=["-created_at"], name="chatbot_art_created_8d96e0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qa_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("question", models.TextField(db_index=True)),
                ("answer", models.TextField()),
                ("topic", models.CharField(db_index=True, max_length=200)),
                ("topic_original", models.CharField(blank=True, max_length=200)),
                ("views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Câu hỏi - Trả lời",
                "verbose_name_plural": "Câu hỏi - Trả lời",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["topic"], name="chatbot_qa_topic_5ca591_idx"),
                    models.Index(
                        fields=["-created_at"], name="chatbot_qa_created_5616dd_idx"
                    ),
                ],
            },
        ),
    ]
